api/urls.py
from django.conf.urls import url, include
from rest_framework.authtoken import views


urlpatterns = [

]

urlpatterns += [


]

core/urls.py
from django.conf.urls import url,include

from core import views

app_name = 'core'


daycare_urls = [
                url(r'^$', views.daycare_list, name='daycare_list'),

                url(r'^create$', views.create_daycare, name='daycare_create'),
                url(r'^(?P<pk>\d+)/', include([
                    url(r'^$',views.daycare_view, name='daycare_view'),
                    url(r'^owner$',views.daycare_owner_edit, name='owner'),
                    url(r'^images$',views.daycare_images, name='images'),
                    url(r'^images/add$',views.daycare_images, name='add_images'),
                    url(r'^edit$',views.daycare_edit, name='edit'),
                    url(r'^delete$',views.daycare_delete, name='delete'),
                    url(r'^contacts$',views.daycare_contacts, name='contacts'),
                    url(r'^contacts/',include([
                        url(r'^create$', views.daycare_contact_create, name='create'),
                        url(r'^(?P<contact_pk>\d+)/', include([
                            # url(r'^$', views.daycare_view, name='view')
                        ]))
                    ]))
                ]))
            ]


urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^details$', views.details, name='details'),
    # url(r'^index/$', views.index2, name='index2'),
    #url(r'^daycare/create/$', views.create_daycare, name='daycare_create'),
    #url(r'^daycare/view/(?P<pk>\d+)/', views.daycare_view, name='daycare_view'),
    url(r'^daycares/', include(daycare_urls)),
    url(r'^listing$', views.listing, name='daycare_listing'),
    url(r'^organisations/', include([
        url(r'^$', views.organisation_list),
        url(r'^create$', views.organisation_create),

        url(r'^(?P<sub_domain>[\w-]+)/', include([

            url(r'^daycares/', include(daycare_urls)),

            #url(r'^$',views.daycare_view, name='view'),
            #url(r'^daycares',views.daycare_list, name='view'),
            #url(r'^images$',views.daycare_images, name='view'),
            # url(r'^images/add$',views.daycare_images, name='view'),
            # url(r'^edit$',views.daycare_edit, name='view'),
            # url(r'^delete$',views.daycare_delete, name='view'),
            # url(r'^contacts$',views.daycare_contacts, name='contacts'),
            # url(r'^contacts/',include([
            #     url(r'^create$', views.daycare_contact_create, name='view'),
            #     url(r'^(?P<contact_pk>\d+)/', include([
            #         # url(r'^$', views.daycare_view, name='view')
            #     ]))
            # ]))
        ]))
    ])),

    url(r'^admins/', include([
        url(r'^create$', views.admin_create),
    ])),

]

hadhari/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url(r"^", include('authentication.urls')),
    url(r"^", include('core.urls', namespace='core')),
    # url(r"^", include("map.urls"), name='map'),

    url(r'^admin/', admin.site.urls),
]
# serve static and media files in development
if settings.DEBUG:
    urlpatterns = urlpatterns \
                  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
                  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.contrib.gis.db import models

from authentication.models import Account
# Create your models here.


class Organisation(models.Model):
    id = models.CharField(max_length=100,unique=True,primary_key=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Admin(models.Model):
    name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=25, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)

    organisation = models.ForeignKey(Organisation,on_delete=models.CASCADE)

    def __str__(self):
        return self.name


# class Category(models.Model):
class Category(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField()

    def __str__(self):
        return self.name

class Service(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField()

    def __str__(self):
        return self.name


class Location(models.Model):
    coordinate = models.PointField(srid=4326)
    accuracy = models.IntegerField(default=0)

    def __str__(self):
        return '{}'.format(self.coordinate)


class Owner(models.Model):
    name = models.CharField(max_length=255)
    literate = models.IntegerField()
    phone_number = models.CharField(max_length=25, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.name


class Daycare(models.Model):
    serial_number = models.IntegerField(unique=True, blank=True, null=True)
    name = models.CharField(max_length=255)
    established_date = models.DateField(blank=True, null=True)
    max_capacity = models.IntegerField(blank=True, null=True)
    avg_children = models.IntegerField(blank=True, null=True)
    helpers = models.IntegerField(blank=True, null=True)
    standards = models.CharField(max_length=5, blank=True, null=True)
    slug = models.CharField(max_length=255)
    status = models.IntegerField()
    min_age = models.IntegerField()
    max_age = models.IntegerField()
    email = models.CharField(max_length=255, blank=True, null=True)
    cell_phone = models.CharField(max_length=15, blank=True, null=True)
    land_line = models.CharField(max_length=15, blank=True, null=True)
    website = models.URLField(blank=True, null=True)

    description = models.TextField(blank=True, null=True)
    owner = models.ForeignKey(Owner,on_delete=models.CASCADE,null=True,blank=True)

    location = models.OneToOneField(Location,models.CASCADE)
    services = models.ManyToManyField(Service)
    categories = models.ManyToManyField(Category)

    organisation = models.ForeignKey(Organisation,on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Image(models.Model):
    name = models.CharField(max_length=255)

    file = models.ImageField(upload_to='daycares')
    daycare = models.ForeignKey(Daycare, models.CASCADE)
    visible = models.BooleanField(default=True)

    weight = models.IntegerField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    created_by = models.ForeignKey(Account,on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name


class Contact(models.Model):
    daycare = models.ForeignKey(Daycare, models.DO_NOTHING)
    phone = models.CharField(max_length=8,unique=True)
    email = models.EmailField(blank=True, null=True)

    def __str__(self):
        return self.phone

core/forms.py
from django import forms
from core.models import Daycare,Owner,Organisation
from authentication.models import Account
from django.template.defaultfilters import slugify
from django.template import loader

from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMultiAlternatives
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

class DaycareForm(forms.ModelForm):

    class Meta:
        model = Daycare
        fields = [
            'serial_number',
            'name',
            'established_date',
            'max_capacity',
            'avg_children',
            'helpers',
            'standards',
            'status',
            'min_age',
            'max_age',
            'email',
            'cell_phone',
            'land_line',
            'website',
            'description',
            'owner',
            # 'location',
            'services',
            'categories'
        ]

    def save(self, commit=True):
        daycare = super(DaycareForm, self).save(commit=False)
        # activity.created_by = self.request.user

        # print(self.cleaned_data)
        daycare.slug = slugify(self.cleaned_data.get('name'))

        if commit:
            daycare.save()

        return daycare


class OwnerForm(forms.ModelForm):
    class Meta:
        model = Owner
        exclude = ()


class OrganisationForm(forms.ModelForm):
    sub_domain = forms.CharField(max_length=100,required=True)

    class Meta:
        model = Organisation
        exclude = ('id',)

    def save(self, commit=False):
        organisation = super(OrganisationForm, self).save(commit=commit)

        organisation.id = self.cleaned_data['sub_domain']
        if commit:
            organisation.save()

        return organisation


class AdminForm(forms.Form):
    email = forms.EmailField()

    def send_mail(self, subject_template_name, email_template_name,
                  context, from_email, to_email, html_email_template_name=None):
        """
        Send a django.core.mail.EmailMultiAlternatives to `to_email`.
        """
        subject = loader.render_to_string(subject_template_name, context)
        # Email subject *must not* contain newlines
        subject = ''.join(subject.splitlines())
        body = loader.render_to_string(email_template_name, context)

        email_message = EmailMultiAlternatives(subject, body, from_email, [to_email])
        if html_email_template_name is not None:
            html_email = loader.render_to_string(html_email_template_name, context)
            email_message.attach_alternative(html_email, 'text/html')

        email_message.send()

    def save(self):
        email = self.cleaned_data.get('email')
        account = Account.objects.create_user(
            email=email,
            password='####',
            access_level=2,
            is_verified = True
        )

        use_https = True
        """
        Generate a one-use only link for resetting password and send it to the
        user.
        """
        context = {
            'email': email,
            'domain': 'domain',
            'site_name': 'site_name',
            'uid': urlsafe_base64_encode(force_bytes(account.pk)).decode(),
            'user': account,
            'token': default_token_generator.make_token(account),
            'protocol': 'https' if use_https else 'http',
        }

        self.send_mail(
            'authentication/registration/password_reset_subject.txt',
            'authentication/registration/password_reset_email.html',
            context,
            'from_email',
            email,
            None,
        )

        return account

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from pyproj import Proj, transform
from django.conf import settings

from core.forms import DaycareForm,OwnerForm
from core.models import Daycare,Organisation
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
import logging


logger = logging.getLogger('prj')


# def index(request):
#     context = {
#         'google_maps_key': settings.GOOGLE_MAPS_API_KEY,
#         'form' : DaycareForm()
#     }
#
#     return render(request,'core/map.html',context)

def index(request):
    context = {
        'google_maps_key': settings.GOOGLE_MAPS_API_KEY,
        'form' : DaycareForm()
    }
    return render(request,'core/index.html',context)

def details(request):
    context = {
        'google_maps_key': settings.GOOGLE_MAPS_API_KEY,
        'form' : DaycareForm()
    }
    return render(request,'core/details.html',context)


def listing(request):

    page = request.GET.get('page', 1)

    daycares = Daycare.objects.all()

    paginator = Paginator(daycares, 20)
    try:
        daycares = paginator.page(page)
    except PageNotAnInteger:
        daycares = paginator.page(1)
    except EmptyPage:
        daycares = paginator.page(paginator.num_pages)

    context = {
        'daycare' : daycare_view,
        'daycares' : daycares,
        'google_maps_key': settings.GOOGLE_MAPS_API_KEY,
        'form' : DaycareForm()
    }
    return render(request,'core/listing.html',context)


def create_daycare(request):
    if request.method == "POST":
        form = DaycareForm(data=request.POST)
        if form.is_valid():
            daycare = form.save()

            return redirect('/daycares/')
    else:
        form = DaycareForm()

    return render(request, 'core/daycare/create.html', {'form':form,'google_maps_key':settings.GOOGLE_MAPS_API_KEY})


def daycare_edit(request,pk):
    daycare = Daycare.objects.get(pk=pk)

    if request.method == "POST":
        form = DaycareForm(data=request.POST)
        if form.is_valid():
            daycare = form.save()

            return redirect('/')
    else:
        form = DaycareForm(instance=daycare)

    return render(request, 'core/daycare/create.html', {'form':form,'google_maps_key':settings.GOOGLE_MAPS_API_KEY})


def daycare_delete(request,pk):
    daycare = Daycare.objects.get(pk=pk)
    if request.method == "POST":
        daycare.delete()
        # todo add success message
        return redirect('/')

    return render(request, 'core/daycare/delete.html', {
        'daycare':daycare,
        'google_maps_key':settings.GOOGLE_MAPS_API_KEY
    })


def daycare_contact_create(request,pk):
    if request.method == "POST":
        form = DaycareForm(data=request.POST)
        if form.is_valid():
            daycare = form.save()


            return redirect('/daycares/')
    else:
        form = DaycareForm()

    return render(request, 'core/daycare/create.html', {'form':form})


def daycare_owner_edit(request,pk):
    daycare = Daycare.objects.get(pk=pk)

    return render(request, 'core/owner/detail.html',{'owner':daycare.owner})


def daycare_view(request, pk):
    daycare = get_object_or_404(Daycare, pk=pk)


    in_projection = Proj(init='epsg:4326')
    out_projection = Proj(init='epsg:3857')

    x, y = transform(in_projection, out_projection, daycare.location.coordinate.x, daycare.location.coordinate.y)

    context = {
        'daycare': daycare,
        'lat': y,
        'lng': x
    }

    return render(request, 'core/daycare/detail.html', context)


def daycare_images(request, pk):
    context = {
        'daycare': get_object_or_404(Daycare, pk=pk)
    }

    return render(request, 'core/daycare/images.html', context)


def daycare_contacts(request, pk):
    context = {
        'daycare': get_object_or_404(Daycare, pk=pk)
    }

    return render(request, 'core/daycare/contacts.html', context)


def daycare_list(request,sub_domain=None):

    in_projection = Proj(init='epsg:4326')
    out_projection = Proj(init='epsg:3857')

    if sub_domain:
        daycares = Daycare.objects.filter(organisation=request.organisation)
    else:
        daycares = Daycare.objects.filter()

    data = []

    # data = { 'data': data }
    for daycare in daycares:
        daycare_ = dict()

        x, y = transform(in_projection, out_projection, daycare.location.coordinate.x, daycare.location.coordinate.y)

        daycare_['lat'] = y
        daycare_['lng'] = x

        daycare_['id'] = daycare.pk
        daycare_['name'] = daycare.name

        data.append(daycare_)

    # contact_groups = ContactGroup.objects.all().order_by('-id')
    # return render(request, 'core/daycare/daycare_list.html', data)
    return JsonResponse(data,safe=False)

from core.forms import AdminForm


def admin_create(request):
    if request.method == "POST":
        form = AdminForm(data=request.POST)

        if form.is_valid():
            admin = form.save()

            return redirect('/')
    else:
        form = AdminForm()

    return render(request, 'core/admin/create.html', {'form':form})

from core.forms import OrganisationForm


def organisation_create(request):
    if request.method == "POST":
        form = OrganisationForm(data=request.POST)
        if form.is_valid():
            organisation = form.save()

            return redirect('/organisations/')
    else:
        form = OrganisationForm()

    return render(request, 'core/organisation/create.html', {'form':form})


def organisation_list(request):

    return render(request, 'core/organisation/list.html', {'organisations':Organisation.objects.all()})

core/templates/core/application.html
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    ================================================== -->
    <title>Daycares | Map</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS
    ================================================== -->
    {% load static %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
          integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">



</head>

<body>

{% block app %}{% endblock %}


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.1.1.min.js" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"
        integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
        crossorigin="anonymous"></script>
{% block script %}{% endblock %}
</body>


</html>

core/templates/core/layout.html
{% extends 'core/application.html' %}

{% block app %}


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">TinyTotos</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item">
                <a class="nav-link" href="#">ll</a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    More
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>


        </ul>

        {% block nav_form %}

{#            <form class="form-inline my-2 my-lg-0">#}
{#                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
{#                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
{#            </form>#}

        {% endblock %}

        <ul class="navbar-nav">

            <li class="nav-item dropdown">
                {% if user.is_authenticated %}

                    <a class="nav-link dropdown-toggle"
                       href="#!"
                       id="navbarDropdownMenuLink"
                       data-toggle="dropdown"
                       aria-haspopup="true"
                       aria-expanded="false">
                        {{ request.user.email }}
                    </a>

                    <div class="dropdown-menu dropdown-menu-right"
                         aria-labelledby="navbarDropdownMenuLink">

                        <a class="dropdown-item" href="/admin/" target="_blank">Django Admin</a>
                        <a class="dropdown-item" href="/admin/logout/">Logout</a>
                    </div>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/login/?next={{ request.path }}">Login</a>
                    </li>

                {% endif %}


            </li>

        </ul>

    </div>
</nav>



    <!-- Page Content -->
    <div class="container-fluid" >
        {% block content %}
        {% endblock %}
    </div>
    <!-- /.container -->


    {% block modal %}
    {% endblock %}
{% endblock %}

core/templates/core/listing.html
{% extends 'frontend/layout_front_listing.html' %}
{% load static %}
{% block content %}

<div class="fs-container">

	<div class="fs-inner-container content">
		<div class="fs-content">

			<!-- Search -->
			<section class="search">

				<div class="row">
					<div class="col-md-12">

							<!-- Row With Forms -->
							<div class="row with-forms">

								<!-- Main Search Input -->
								<div class="col-fs-6">
									<div class="input-with-icon">
										<i class="sl sl-icon-magnifier"></i>
										<input type="text" placeholder="What are you looking for?" value=""/>
									</div>
								</div>

								<!-- Main Search Input -->
								<div class="col-fs-6">
									<div class="input-with-icon location">

										<input type="text" placeholder="Destination, city, address" value=""/>
										<a href="#"><i class="fa fa-dot-circle-o"></i></a>
									</div>
								</div>


								<!-- Filters -->
								<div class="col-fs-12">

									<!-- Panel Dropdown / End -->
									<div class="panel-dropdown">
										<a href="#">Categories</a>
										<div class="panel-dropdown-content checkboxes categories">

											<!-- Checkboxes -->
											<div class="row">
												<div class="col-md-6">
													<input id="check-1" type="checkbox" name="check" checked class="all">
													<label for="check-1">All Categories</label>

													<input id="check-2" type="checkbox" name="check">
													<label for="check-2">Shops</label>

													<input id="check-3" type="checkbox" name="check">
													<label for="check-3">Hotels</label>
												</div>

												<div class="col-md-6">
													<input id="check-4" type="checkbox" name="check" >
													<label for="check-4">Eat & Drink</label>

													<input id="check-5" type="checkbox" name="check">
													<label for="check-5">Fitness</label>

													<input id="check-6" type="checkbox" name="check">
													<label for="check-6">Events</label>
												</div>
											</div>

											<!-- Buttons -->
											<div class="panel-buttons">
												<button class="panel-cancel">Cancel</button>
												<button class="panel-apply">Apply</button>
											</div>

										</div>
									</div>
									<!-- Panel Dropdown / End -->

									<!-- Panel Dropdown -->
									<div class="panel-dropdown wide">
										<a href="#">More Filters</a>
										<div class="panel-dropdown-content checkboxes">

											<!-- Checkboxes -->
											<div class="row">
												<div class="col-md-6">
													<input id="check-a" type="checkbox" name="check">
													<label for="check-a">Elevator in building</label>

													<input id="check-b" type="checkbox" name="check">
													<label for="check-b">Friendly workspace</label>

													<input id="check-c" type="checkbox" name="check">
													<label for="check-c">Instant Book</label>

													<input id="check-d" type="checkbox" name="check">
													<label for="check-d">Wireless Internet</label>
												</div>

												<div class="col-md-6">
													<input id="check-e" type="checkbox" name="check" >
													<label for="check-e">Free parking on premises</label>

													<input id="check-f" type="checkbox" name="check" >
													<label for="check-f">Free parking on street</label>

													<input id="check-g" type="checkbox" name="check">
													<label for="check-g">Smoking allowed</label>

													<input id="check-h" type="checkbox" name="check">
													<label for="check-h">Events</label>
												</div>
											</div>

											<!-- Buttons -->
											<div class="panel-buttons">
												<button class="panel-cancel">Cancel</button>
												<button class="panel-apply">Apply</button>
											</div>

										</div>
									</div>
									<!-- Panel Dropdown / End -->

									<!-- Panel Dropdown -->
									<div class="panel-dropdown">
										<a href="#">Distance Radius</a>
										<div class="panel-dropdown-content">
											<input class="distance-radius" type="range" min="1" max="100" step="1" value="50" data-title="Radius around selected destination">
											<div class="panel-buttons">
												<button class="panel-cancel">Disable</button>
												<button class="panel-apply">Apply</button>
											</div>
										</div>
									</div>
									<!-- Panel Dropdown / End -->

								</div>
								<!-- Filters / End -->

							</div>
							<!-- Row With Forms / End -->

					</div>
				</div>

			</section>
			<!-- Search / End -->


		<section class="listings-container margin-top-30">
			<!-- Sorting / Layout Switcher -->
			<div class="row fs-switcher">

				<div class="col-md-6">
					<!-- Showing Results -->
					<p class="showing-results">{{ daycare.count }} Results Found </p>
				</div>

			</div>


			<!-- Listings -->
			<div class="row fs-listings">

                {% for daycare in daycares %}

				<!-- Listing Item -->
				<div class="col-lg-12 col-md-12">
					<div class="listing-item-container list-layout" data-marker-id="2">
						<a href="{% url 'core:daycare_view' pk=daycare.pk%}" class="listing-item">

							<!-- Image -->
							<div class="listing-item-image">
								<img src="{% static 'front/images/baby_icon.png' %}" alt="">
								<span class="tag">Daycare</span>
							</div>

							<!-- Content -->
							<div class="listing-item-content">

								<div class="listing-item-inner">
								<h3>{{ daycare.name }}</h3>
								<span>{{ daycare.owner }}</span>

							</div>
						</a>
					</div>
				</div>
				<!-- Listing Item / End -->
                {% endfor %}

			</div>
			<!-- Listings Container / End -->


			<!-- Pagination Container -->
			<div class="row fs-listings">
				<div class="col-md-12">

					<!-- Pagination -->
					<div class="clearfix"></div>
					<div class="row">
						<div class="col-md-12">
							<!-- Pagination -->
							<div class="pagination-container margin-top-15 margin-bottom-40">
								<nav class="pagination">
									<ul>

                                        {% if daycares.has_other_pages %}


                                              {% if daycares.has_previous %}
                                              <li><a href="?page={{ users.previous_page_number }}">&laquo;</a></li>
                                            {% else %}
                                              <li class="disabled"><span>&laquo;</span></li>
                                            {% endif %}
                                            {% for i in daycares.paginator.page_range %}
                                              {% if daycares.number == i %}
                                                  <li><a href="/listing?page={{ i }}" class="current-page">{{ i }}</a></li>
                                              {% else %}
{#                                                <li><a href="/listing?page={{ i }}">{{ i }}</a></li>#}
                                              {% endif %}
                                            {% endfor %}
                                            {% if daycares.has_next %}


										    <li><a href="?page={{ daycares.next_page_number }}"><i class="sl sl-icon-arrow-right"></i></a></li>


                                            {% else %}
                                              <li class="disabled"><span>&raquo;</span></li>
                                            {% endif %}




                                        {% endif %}




									</ul>
								</nav>
							</div>
						</div>
					</div>
					<div class="clearfix"></div>
					<!-- Pagination / End -->

					<!-- Copyrights -->
					<div class="copyrights margin-top-0">© 2017 Listeo. All Rights Reserved.</div>

				</div>
			</div>
			<!-- Pagination Container / End -->
		</section>

		</div>
	</div>
	<div class="fs-inner-container map-fixed">

		<!-- Map -->
{#		<div id="map-container">#}
{#		    <div id="map" data-map-zoom="9" data-map-scroll="true">#}
{#		        <!-- map goes here -->#}
{#		    </div>#}
{#		</div>#}
    <div id="map" data-map-zoom="12">
        <!-- map goes here -->
    </div>

	</div>
</div>



{% endblock  %}